Common/config/formatter-plugins.config.php
Common/src/Common/Service/Table/Formatter/ExternalConversationMessage.php

Case worker can select a conversation, they are then taken to a page where they can view the messages related to that conversation.
Related issue: [VOL-4805](https://dvsa.atlassian.net/browse/VOL-4805)

feat: Conversation message list table formatter

---

Common/src/Common/Form/Model/Fieldset/GenerateContinuationDetails.php

Removes the prepending slash from the `service_name` for `GenerateContinuationDetails`.
Related issue: https://dvsa.atlassian.net/browse/VOL-4864

fix: fix `GenerateContinuationDetails` `service_name`

---

Common/src/Common/Form/Elements/Types/AbstractInputSearch.php
test/Common/src/Common/Form/Elements/Types/AbstractInputSearchTest.php

When `$this->messages` were empty, `current($this->messages)` returns `false`, contrary to the return type.
Related issue: https://dvsa.atlassian.net/browse/VOL-4870

fix: fix type error in `AbstractInputSearch` when `this->messages` is empty

---

Common/src/Common/Controller/Lva/AbstractAddressesController.php
Common/src/Common/Form/Element/OptionalSelect.php
Common/src/Common/Form/Elements/Types/PostcodeSearch.php
Common/src/Common/FormService/Form/Lva/OperatingCentre/CommonOperatingCentre.php
test/Common/src/Common/Form/Element/OptionalSelect.php

The Laminas form `Select` to mark as not required by default. This PR extends the Laminas form `Select` element and marks it as not required by default - this is weird decision by Laminas, the other elements are in fact _not_ required by default. This element is useful for postcode lookups where they are form elements but can be entered manually.
Alternative would be setting `setRequired` each time the "Search postcode" is used, this seemed more appropriate.
Related issue: https://dvsa.atlassian.net/browse/VOL-4875 & https://dvsa.atlassian.net/browse/VOL-4855

Add optional select form element

---

Common/src/Common/Form/Model/Fieldset/Address.php
Common/src/Common/Form/Model/Fieldset/AddressOptional.php

Keep `SearchPostcode` fieldset at the top of the `Address` fieldset.
Elements are injected first into a `PriorityList`, then fieldsets. Without priority, the sequential insert order is used, this was putting the `SearchPostcode` fieldset _after_ the address elements instead of at the top of the parent fieldset.
Ticket: https://dvsa.atlassian.net/browse/VOL-4887

fix: keep `SearchPostcode` fieldset at the top of the `Address` fieldset

---

Common/src/Common/Service/Qa/Custom/CertRoadworthiness/MotExpiryDateFieldsetPopulator.php
Common/src/Common/Service/Qa/Custom/EcmtRemoval/PermitStartDateFieldsetPopulator.php

Add the new `create_empty_option` (introduced in Laminas v3) to the `DateSelect` field otherwise you get todays date.
Related issue: https://dvsa.atlassian.net/browse/VOL-4903

fix: add `create_empty_option` to date fields that can be empty

---

Common/src/Common/Form/Model/Form/Lva/Fieldset/LicenceHistoryData.php
Common/src/Common/Form/Model/Form/Lva/Fieldset/LicenceHistoryEu.php
Common/src/Common/Form/Model/Form/Lva/Fieldset/TransportManager/PreviousHistory.php
Common/src/Common/Form/Model/Form/Lva/Fieldset/TransportManager/Responsibilities.php
Common/src/Common/Form/Model/Form/Lva/TransportManagerDetails.php

If a fieldset contains a mix of fieldsets and elements the fieldsets are always processed afterwards - resulting in the form being ordered differently - elements first, followed by any fieldsets.
Related issue: https://dvsa.atlassian.net/browse/VOL-4896 & https://dvsa.atlassian.net/browse/VOL-4894

fix: add priority to forms to order elements/fieldsets better

---

Common/src/Common/Service/Table/Formatter/DashboardTmApplicationStatusFactory.php
Common/src/Common/Service/Table/Formatter/DataRetentionAssignedToFactory.php

Fix issue with casing for `viewHelperManager`.
Related issue: https://dvsa.atlassian.net/browse/VOL-4907

fix: fix casing of `ViewHelperManager` in call to service manager

---

Common/config/formatter-plugins.config.php
Common/src/Common/Service/Table/Formatter/ExternalConversationLink.php
Common/src/Common/Service/Table/Formatter/ExternalConversationStatus.php
Common/src/Common/Service/Table/Formatter/ExternalConversationStatusFactory.php

External message list should be split in to two columns with status in the right column.
Related issue: [VOL-4805](https://dvsa.atlassian.net/browse/VOL-4805)

feat: Message list split in to two columns

---

Common/config/module.config.php
Common/src/Common/Controller/Plugin/ElasticSearchFactory.php

The projects were using a mix of `Navigation` and `navigation` resulting in two different objects - this caused issues with navigation as two different objects were being mutated and used.
I went with `navigation` even though it was a larger refactor due to that being the alias that is registered in the upstream package: https://github.com/laminas/laminas-navigation/blob/2f39ab2f929d23da89bbb4401efdccb6e72eaf68/src/ConfigProvider.php#L33.
Related issue:  https://dvsa.atlassian.net/browse/VOL-4900 & https://dvsa.atlassian.net/browse/VOL-4915

fix: consolidate `Navigation` and `navigation`

---

Common/src/Common/Form/Model/Form/Lva/Fieldset/TransportManager/Details.php

Add priority to form elements and fieldsets to correctly order form.
Related issue: https://dvsa.atlassian.net/browse/VOL-4894

fix: add `priority` to correctly order TM details form

---

Common/config/module.config.php

lowercasing entry in module.config.php, now custom helper is being used. Fixes rendering of some elements to format defined in the pattern annotation
Related issue: [VOL-4931](https://dvsa.atlassian.net/browse/VOL-4932)

fix: lowercasing formdatetimeselect. Custom helper not being used

---

Common/src/Common/Form/Elements/Custom/EcmtNoOfPermitsElement.php
Common/src/Common/Service/Qa/Custom/Bilateral/NoOfPermitsElement.php

This value is passed to: `\Laminas\Form\View\Helper\AbstractHelper::translateHtmlAttributeValue` which is now typed to a `string`.
Related issue: https://dvsa.atlassian.net/browse/VOL-4935

fix: update `MAX_LENGTH` to `string` to fix type error

---

Common/src/Common/Controller/Lva/AbstractCommunityLicencesController.php

Fixes the undefined variable `$formHelper` - this is now a class property.
Related issue: https://dvsa.atlassian.net/browse/VOL-4988

fix: fix undefined `formHelper` variable

---

Common/config/module.config.php

As L3 made the Service Manager case sensitive, `->get('FormCollection')` would return the Laminas class rather than our overwritten class.
Related issue: https://dvsa.atlassian.net/browse/VOL-5055

fix: add `FormCollection` overwrite to service manager

---

Common/src/Common/Service/Table/TableBuilder.php
Common/view/table/layouts/default.phtml
Common/view/table/layouts/table.phtml

Show conversation title on conversation page - support hiding table header
Related issue: [VOL-5031](https://dvsa.atlassian.net/browse/VOL-5031)

feat: TableBuilder hide title

---

Common/src/Common/Rbac/Service/Permission.php
test/Common/src/Common/Rbac/Service/PermissionTest.php

Add `isSelf` to `Permission` service to provide a method to check if the user ID provided is the current logged in user.
Related issue: Regression from https://dvsa.atlassian.net/browse/VOL-5103

fix: add `isSelf` to `Permission` service

---

Common/src/Common/Service/Table/Formatter/AbstractConversationMessage.php

Add a footer to internal to show the first operator to read the message.
Related issue: [VOL-5082](https://dvsa.atlassian.net/browse/VOL-5082)

feat: Message footer showing operator first read

---

Common/src/Common/Data/Object/Search/Aggregations/Terms/DeletedStatus.php
Common/src/Common/Data/Object/Search/Aggregations/Terms/MergedStatus.php
Common/src/Common/Data/Object/Search/Aggregations/Terms/TermsAbstract.php
Common/src/Common/Data/Object/Search/People.php
Common/src/Common/Service/Data/Search/Search.php

Allow filtering of transport managers by merged and deleted status.
Related issue: [VOL-3539](https://dvsa.atlassian.net/browse/VOL-3539)

feat: Null check elastic search terms for filtering transport managers

---

Common/src/Common/Form/View/Helper/Extended/PrepareAttributesTrait.php
test/Common/src/Common/Form/View/Helper/Extended/FormRadioTest.php
test/Common/src/Common/Form/View/Helper/Extended/PrepareAttributesTraitTest.php

Translator was trying to translate an int - we had code tin place to sort this and it had been removed
Related issue: [VOL-5217](https://dvsa.atlassian.net/browse/VOL-5217)

fix: Reinstate casting attributes to string

---

Common/src/Common/Controller/Lva/AbstractGoodsVehiclesController.php

Fixes: `AbstractGoodsVehiclesController::handleCrudAction() must be of the type array, null given`. Regressed from the static analysis ticket.
Related issue: https://dvsa.atlassian.net/browse/VOL-5230

fix: fix regression in `AbstractGoodsVehiclesController.php`

---

Common/src/Common/Service/Data/Search/Search.php
test/Common/src/Common/Service/Data/Search/SearchTest.php

empty() treating string '0' as empty, wrong assumption for filters.
Related issue: [VOL-3539](https://dvsa.atlassian.net/browse/VOL-3539)

fix: String '0' should not be ignore when running filtering on search

---

Common/src/Common/Rbac/Service/Permission.php
Common/src/Common/RefData.php
test/Common/src/Common/Rbac/Service/PermissionTest.php

Permission service can now check for permission to manage selfservice users. Fixes bug on manage users page.
Related issue: [VOL-5243](https://dvsa.atlassian.net/browse/VOL-5243)

fix: VOL-5243 permission service can now check for manage selfserve user permissions

---

composer.json

Locked PHP version to **~8.0.0**
Related issue: https://dvsa.atlassian.net/browse/VOL-4747

fix: locked php version to ~8.0.0

---

Common/view/pages/continuation-success.phtml

On completing a digital continuation is supposed to show heading "What happens next" with text underneath stating "Your licence documentation and vehicle discs will be sent within 5 working days" (see original story OLCS-16468. Alternative text when there are no discs detailed in OLCS-17779.)
However, the text underneath the "What happens next" heading is currently missing.
Related issue: [VOL-3003](https://dvsa.atlassian.net/browse/VOL-3003)

fix: What happens next detail missing text

---

Common/src/Common/Data/Mapper/DefaultMapper.php
Common/src/Common/Data/Mapper/Licence/Surrender/CommunityLicence.php
Common/src/Common/Data/Mapper/Licence/Surrender/OperatorLicence.php

Mapper methods are called statically. As of PHP 8.0 calling non-static methods statically throws an error.
Related issue: https://dvsa.atlassian.net/browse/VOL-5448

fix: convert methods `mapFromForm` and `mapFromErrors` to static

---

Common/src/Common/Form/Model/Form/Lva/Fieldset/LicenceLicenceVehicle.php
Common/src/Common/Form/Model/Form/Lva/Fieldset/LicenceVehicle.php
Common/src/Common/Form/Model/Form/Lva/Fieldset/LicenceVehicleAppVar.php

Latest Laminas Form no longer allows for our custom HTML as it strips out <> characters. Returning formatting to the default INTL pattern.
Related issue: [VOL-5466](https://dvsa.atlassian.net/browse/VOL-5466)

fix: VOL-5466 compatibility with latest Laminas form

---

Common/config/language/partials/en_GB/markup-messaging-new-conversation-timeframe.phtml

Make the response timeframe text under create new message thread on self-serve an editable translation
Related issue: [VOL-5525](https://dvsa.atlassian.net/browse/VOL-5525)

feat: make messaging timeframe string an editable translation

---

Common/config/language/partials/en_GB/markup-messaging-new-conversation-timeframe.phtml

Remove call to translate - this view is actually a fallback for the same translation key which was just not defined.

fix: Revert translation key fallback view

---

Common/src/Common/Service/Table/Formatter/AbstractConversationMessage.php
Common/src/Common/Service/Table/Formatter/ExternalConversationMessage.php

remove caseworkers family name in messages on `selfserve`

feat: remove caseworkers family name on `selfserve`

---

Common/src/Common/Preference/Language.php
test/Common/src/Common/Preference/LanguageTest.php

Fixes a console warning regarding langPref cookie
Related issue: [VOL-5555]

feat: Set SameSite cookie attr to clean up some console warnings

---

Common/src/Common/Service/Table/Formatter/ExternalConversationStatus.php
test/Common/src/Common/Service/Table/Formatter/ExternalConversationStatusTest.php

Lowercase some UPPERCASE Tag labels.
Related issue: [VOL-5669](https://dvsa.atlassian.net/browse/VOL-5669)

fix: Make messaging status tags the correct case for GDS frontend

---

Common/src/Common/Service/Table/Formatter/EbsrDocumentStatus.php
Common/src/Common/Service/Table/Formatter/EbsrVariationNumber.php
test/Common/src/Common/Service/Table/Formatter/EbsrDocumentStatusTest.php
test/Common/src/Common/Service/Table/Formatter/EbsrVariationNumberTest.php

Fix EBSR Tag case in 2 table columns
Related issue: [VOL-5698](https://dvsa.atlassian.net/browse/VOL-5698)

fix: correct case of EBSR Variation and File Status tags.

---

Common/src/Common/Form/Elements/InputFilters/Phone.php
test/Common/src/Common/Form/Elements/InputFilters/PhoneRequiredTest.php
test/Common/src/Common/Form/Elements/InputFilters/PhoneTest.php

Fix an input pattern causing console errors - align it to form validator regex.
Related issue: [VOL-5696](https://dvsa.atlassian.net/browse/VOL-5696)

fix: fix pattern escape console error align with validator

---

Common/src/Common/Service/Table/Formatter/InternalConversationLink.php

No conversations were being shown when making a variation **IF** a conversation was made on the licence.

fix: show conversation for variations vol 5661

---

Common/src/Common/View/Helper/PersonName.php
test/Common/src/Common/View/Helper/PersonNameTest.php

Fix to refdata array being presented as "title" property in PersonName helper.
Related issue: [VOL-5764](https://dvsa.atlassian.net/browse/VOL-5764)

fix: add PersonName helper support for title field RefData array.

---

Common/src/Common/Form/Model/Form/Lva/UploadEvidence.php

Set priority of  submit button so it renders at the bottom of the form.
Related issue: [VOL-5830](https://dvsa.atlassian.net/browse/VOL-5830)

fix: ensure submit button renders at the end of the Submit evidence form

---

Common/src/Common/Form/Model/Form/Lva/BusinessDetails.php

Remove the option to change correspondence type on selfserve.
Internal users can still change the correspondence type if needed.
Related issue: [5774](https://dvsa.atlassian.net/browse/VOL-5774)
https://github.com/dvsa/olcs-etl/pull/70
https://github.com/dvsa/vol-app/pull/428

feat: remove option to change correspondence type

---

Common/view/table/layouts/dashboard-licences.phtml

Fix wrongly positioned status when `status = 'Surrender Under Consideration'`
Related issue: [5891](https://dvsa.atlassian.net/jira/software/c/projects/VOL/boards/721?selectedIssue=VOL-5891&sprints=4520)

fix: wrongly positioned status

---

Common/src/Common/RefData.php

Operator user type wasn't available in RefData list
Related issue: [VOL-4718](https://dvsa.atlassian.net/browse/VOL-4718)

feat: operator user type now avialable in RefData

---

Common/src/Common/Form/Elements/Types/FileUploadList.php

When a document has been uploaded a tag will be added to notify the user that the the operation was successful 
Related issue: [VOL-5986](https://dvsa.atlassian.net/browse/VOL-5986)

feat: notify user document has been uploaded

---

Common/src/Common/Service/Table/Formatter/AbstractConversationMessage.php
Common/src/Common/Service/Table/Formatter/ExternalConversationMessage.php

Fixing a bug where messages are hidden when a user, that is part of the conversation, is deleted.
Related issue: [VOL-5987](https://dvsa.atlassian.net/browse/VOL-5987)
[vol-app#668](https://github.com/dvsa/vol-app/pull/668)
[VOL-5987]: https://dvsa.atlassian.net/browse/VOL-5987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: hidden messages when a user is deleted

---

Common/src/Common/Controller/Traits/GenericUpload.php

Set unlink flag for deletions happening from upload form while user is choosing documents to upload
Related issue: [VOL-5967](https://dvsa.atlassian.net/browse/VOL-5967)
[VOL-5967]: https://dvsa.atlassian.net/browse/VOL-5967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: set unlink flag so unwanted uploads are unlinked from licence in event history

---

Common/src/Common/Controller/Lva/AbstractBusinessDetailsController.php
Common/src/Common/FormService/Form/Lva/BusinessDetails/AbstractBusinessDetails.php
test/Common/src/Common/FormService/Form/Lva/BusinessDetails/AbstractBusinessDetailsTest.php

Remove subsidiary companies option for PSV applications on both internal and self serve.
Related issue: [VOL-6122](https://dvsa.atlassian.net/browse/VOL-6122)
[VOL-6122]: https://dvsa.atlassian.net/browse/VOL-6122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: remove subsidiary companies option for PSV applications

---

Common/src/Common/Service/Table/Formatter/AbstractConversationMessage.php
Common/src/Common/Service/Table/Formatter/ExternalConversationLink.php
Common/src/Common/Service/Table/Formatter/FormatterPluginManagerInterface.php
Common/src/Common/Service/Table/Formatter/InternalConversationLink.php
test/Common/src/Common/Form/Elements/Custom/DateTimeSelectTest.php
test/Common/src/Common/Service/Table/Formatter/AbstractConversationMessageTest.php
test/Common/src/Common/Service/Table/Formatter/ExternalConversationLinkTest.php
test/Common/src/Common/Service/Table/Formatter/InternalConversationLinkTest.php
test/Common/src/Common/View/Helper/DateTimeTest.php

Self serve and internal messaging have been using the created on date directly from the database (UTC) without formatting the timezone with Europe/London to account for BST and winter clock changes. Created new tests for the changes and updated existing ones. 
Related issue: [VOL-6295](https://dvsa.atlassian.net/browse/VOL-6295)
[VOL-6295]: https://dvsa.atlassian.net/browse/VOL-6295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update time on VOL messaging to use correct timezone

---

Common/src/Common/Controller/Lva/AbstractBusinessDetailsController.php

Removes a query that retrieves an application, as there is a function in the abstract controller that gives the required data 
Related issue: [VOL-6122](https://dvsa.atlassian.net/browse/VOL-6122)
[VOL-6122]: https://dvsa.atlassian.net/browse/VOL-6122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: remove defective query

---

Common/src/Common/View/Helper/Version.php
Common/view/helper/version.phtml
test/Common/src/Common/View/Helper/VersionTest.php

This PR significantly enhances the Version ViewHelper by adding conditional rendering capabilities, implementing configuration safety, extracting templates to separate view files, implementing security improvements, and ensuring comprehensive test coverage with PHP 8.2 compatibility.
- **Conditional Rendering**: Added `show_information_bar` config option to control when the version component displays
- **Template Separation**: Extracted HTML template to `Common/view/helper/version.phtml` for better maintainability
- **Semantic Default Values**: Distinguished between `'undefined'` (missing config) and `'empty'` (explicitly set but empty)
- **Public Constants**: Exposed `TEMPLATE_PATH`, `DEFAULT_UNDEFINED`, and `DEFAULT_EMPTY` for reusability
- **Constructor Optimization**: Moved all config …

refactor: enhance Version ViewHelper with conditional rendering, config safety and extracted view

---

Common/src/Common/Controller/Plugin/Redirect.php
composer.json

This PR removes the deprecated laminas-json and laminas-serializer packages and replaces their usage with native PHP json_encode() and json_decode() functions. This change is driven by Laminas abandoning these legacy libraries as announced by their technical steering committee.
- Remove laminas/laminas-serializer dependencies from composer.json files
- Replaces Laminas JSON serialization/deserialization with native PHP JSON functions
https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2024-11-04-TSC-Minutes.md#archive--abandon-various-legacy-libraries
Related issue: [VOL-6098](https://dvsa.atlassian.net/browse/VOL-6098)
[VOL-6098]: https://dvsa.atlassian.net/browse/VOL-6098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …

feat: vol-6098 removed laminas-serializer package and laminas-json from relevant code
