dvsa/olcs-common

- Common/config/formatter-plugins.config.php
- Common/src/Common/Service/Table/Formatter/InternalConversationMessage.php
- Common/src/Common/Service/Table/Formatter/InternalLicenceConversationLink.php
- Common/src/Common/Service/Table/Formatter/InternalLicenceConversationLinkFactory.php
Adds a view for messages in a Conversation
Related issue: [VOL-4576](https://dvsa.atlassian.net/browse/VOL-4576)
Original GitLab PR for reference: https://repo.olcs.dev-dvsacloud.uk/olcs/olcs-common/-/merge_requests/1703
> feat: VOL-4576 List Messages in Conversation

- composer.json
Switch to dev-project/messaging for olcs-transfer
> feat: composer olcs-transfer dev-project/messaging

- Common/src/Common/Service/Data/Search/SearchType.php
- Common/src/Common/Service/Data/Search/SearchTypeManager.php
- Common/src/Common/Service/Data/Search/SearchTypeManagerFactory.php
- test/Common/src/Common/Service/Data/Search/SearchTypeTest.php
Search fixes for Laminas 3 (impacts both Internal and Selfserve)
Related issue: [VOL-4847](https://dvsa.atlassian.net/browse/VOL-4847)
> fix: VOL-4847 get search working with Laminas 3

- Common/config/language/partials/en_GB/markup-convictions-and-penalties-guidance-gb.phtml
Update the convictions and penalties guidance.
Related issue: https://dvsa.atlassian.net/browse/VOL-4821
> feat: update Convictions and Penalties guidance

- Common/config/module.config.php
Rename `LicenceChecklist` to `licenceChecklist`.
Related issue: https://dvsa.atlassian.net/browse/VOL-4910
> fix: rename `LicenceChecklist` to `licenceChecklist`

- Common/config/formatter-plugins.config.php
- Common/src/Common/Service/Table/Formatter/ExternalConversationLinkFactory.php
- Common/src/Common/Service/Table/Formatter/InternalConversationLink.php
- Common/src/Common/Service/Table/Formatter/InternalConversationLinkFactory.php
Adds messaging to the application/ routes.
Related issue: [TBC](TBC)
> feat: Extend support of messaging to application nav

- Common/src/Common/Filter/DecompressToTmpDelegatorFactory.php
- Common/src/Common/Service/Table/Formatter/FormatterPluginManager.php
Tidy up laminas 2.5 compatibility code
Related issue: [VOL-3761](https://dvsa.atlassian.net/browse/VOL-3761)
> chore: Tidy up laminas 2 3 compatability vol 3761

- Common/src/Common/RefData.php
Add const for permission
Related issue: [VOL-5188](https://dvsa.atlassian.net/browse/VOL-5188)
> feat: Add list conversations permission const

- Common/src/Common/Controller/Traits/GenericMethods.php
Unable to generate or upload new document
Related issue: [VOL-5189](https://dvsa.atlassian.net/browse/VOL-5189)
> fix: Consistent callback call

- Common/src/Common/Data/Object/Search/People.php
Remove deleted search filter
Related issue: [VOL-3539](https://dvsa.atlassian.net/browse/VOL-3539)
> feat: Remove deleted status filter on search

- Common/src/Common/Service/Table/Formatter/AbstractConversationMessage.php
Don't show first ready by for message if it's the author
Related issue: [VOL-5196](https://dvsa.atlassian.net/browse/VOL-5196)
> fix: Don't show first ready by for message if it's the author

- Common/src/Common/Service/Table/TableBuilder.php
- Removed support for non-FQCN
> fix: removed non-FQCN support in TableBuilder

- Common/src/Common/Controller/Lva/AbstractSafetyController.php
- Common/src/Common/Controller/Lva/AbstractTrailersController.php
- Common/src/Common/Controller/Lva/AbstractVehiclesPsvController.php
> fix: restore fallback CRUD actions

- Common/src/Common/Data/Object/Search/Aggregations/Terms/TermsAbstract.php
- Common/src/Common/Data/Object/Search/Aggregations/Terms/TransportManagerLicenceStatus.php
- Common/src/Common/Data/Object/Search/People.php
- Common/src/Common/assets/js/inline/people-search.js
Allow further filtering of TM's in search
Related issue: [VOL-5211](https://dvsa.atlassian.net/browse/VOL-5211)
> feat: TM search filter by app/licence

- Common/src/Common/Controller/Lva/AbstractDiscsController.php
- Common/src/Common/Controller/Lva/AbstractLicenceHistoryController.php
- Common/src/Common/Controller/Lva/Adapters/AbstractPeopleAdapter.php
- Common/src/Common/Controller/Lva/Adapters/VariationPeopleAdapter.php
- Common/src/Common/Controller/Traits/StoredCardsTrait.php
- Common/src/Common/FormService/Form/Lva/AbstractGoodsVehicles.php
- Common/src/Common/FormService/Form/Lva/BusinessDetails/AbstractBusinessDetails.php
- Common/src/Common/FormService/Form/Lva/BusinessType/AbstractBusinessType.php
- Common/src/Common/FormService/Form/Lva/CommunityLicences/AbstractCommunityLicences.php
- Common/src/Common/FormService/Form/Lva/ConditionsUndertakings/AbstractConditionsUndertakings.php
- Common/src/Common/FormService/Form/Lva/LicenceHistory.php
- Common/src/Common/FormService/Form/Lva/PsvDiscs.php
- Common/src/Common/FormService/Form/Lva/PsvVehicles.php
- Common/src/Common/FormService/Form/Lva/TaxiPhv.php
- Common/src/Common/FormService/Form/Lva/TransportManager/AbstractTransportManager.php
- Common/src/Common/FormService/Form/Lva/Undertakings.php
- Common/src/Common/FormService/Form/Lva/VehiclesDeclarations.php
- Common/src/Common/Service/Data/Search/Search.php
- Common/src/Common/Service/Helper/FormHelperService.php
- composer.json
- test/Common/src/Common/Controller/Lva/AbstractVehiclesDeclarationsControllerTest.php
Related issue: [JIRA_TICKET_NUMBER](LINK_TO_JIRA_TICKET)
> refactor: remove typing breaking selfserve

- Common/src/Common/Data/Object/Search/Aggregations/Terms/TermsAbstract.php
- Common/src/Common/Data/Object/Search/Aggregations/Terms/TransportManagerLicenceStatus.php
- Common/src/Common/Data/Object/Search/ComplexTermInterface.php
- Common/src/Common/Data/Object/Search/InternalSearchAbstract.php
- Common/src/Common/Service/Data/Search/Search.php
- Common/src/Common/Service/Data/Search/SearchType.php
- test/Common/src/Common/Service/Data/Search/SearchTypeTest.php
Allow filtering by active TM's only
Related issue: [VOL-5211](https://dvsa.atlassian.net/browse/VOL-5211)
> feat: Filter active TM's only

- Common/config/language/partials/en_GB/markup-right-first-time.phtml
Change wording on Are You Ready to apply page regarding the video embed.
Related issue: [VOL-5275](https://dvsa.atlassian.net/browse/VOL-5275)
> feature: Change wording on Are You Ready page re: guidance video.

- Common/src/Common/Form/Model/Form/Lva/UploadEvidence.php
Form field missing for self serve upload.
> fix: Missing form field

- Common/src/Common/Controller/Lva/Traits/CrudTableTrait.php
Remove return type causing issues on various journey.=s
Related issue: [VOL-5388](https://dvsa.atlassian.net/browse/VOL-5388)
> fix: Remove return type causing errors on may journeys

- Common/src/Common/Controller/Continuation/FinancesController.php
- Common/src/Common/Controller/Continuation/OtherFinancesController.php
- Common/src/Common/Controller/Continuation/PaymentController.php
- Common/src/Common/Controller/ErrorController.php
- Common/src/Common/Controller/Lva/AbstractAddressesController.php
- Common/src/Common/Controller/Lva/AbstractLicenceHistoryController.php
- Common/src/Common/Controller/Lva/AbstractVehiclesDeclarationsController.php
- Common/src/Common/Controller/Lva/Schedule41Controller.php
- Common/src/Common/Controller/Lva/Variation/AbstractTypeOfLicenceController.php
Remove controller action return typing added in upgrade causing issues with journeys.
Related issue: [VOL-5433](https://dvsa.atlassian.net/browse/VOL-5433)
> fix: Fix journey issues caused by typing added in php 8 upgrade

- Common/src/Common/Service/Helper/DataHelperService.php
Fix broken journey for Task Allocation Rules
Related issue: [VOL-5439](https://dvsa.atlassian.net/browse/VOL-5439)
> fix: Remove typing breaking journeys

- Common/src/Common/Util/Escape.php
Remove typing as null is present in some journeys
> fix: Remove typing from more areas breaking journeys

- Common/src/Common/FeatureToggle.php
Add toggle for switching over to new address service
Related issue: [VOL-5336](https://dvsa.atlassian.net/browse/VOL-5336)
> feat: feature toggle for dvsa address service

- Common/src/Common/Controller/Lva/Adapters/VariationPeopleAdapter.php
Related issue: [VOL-5389](https://dvsa.atlassian.net/browse/VOL-5389)
> fix: VOL-5389 Variation and Application now call the correct Application command

- Common/src/Common/Data/Object/Search/People.php
- Common/src/Common/Service/Table/Formatter/SearchPeopleName.php
- Common/src/Common/Service/Table/Formatter/SearchPeopleNameFactory.php
- Common/src/Common/Service/Table/Formatter/SearchPeopleRecord.php
- test/Common/src/Common/Data/Object/Search/PeopleTest.php
Historic TM table has been removed, this removed the associated app code
Related issue: [VOL-4529](https://dvsa.atlassian.net/browse/VOL-4529)
> feat: VOL-4529 remove historic tm code

- Common/src/Common/RefData.php
Docman support has been removed from the app
Related issue: [VOL-4635](https://dvsa.atlassian.net/browse/VOL-4635)
> refactor!: VOL-4635 remove docman support

- Common/config/language/partials/en_GB/markup-messaging-new-conversation-timeframe.phtml
> fix: Revert translation key fallback view

- Common/src/Common/Service/Table/Formatter/AccessedCorrespondence.php
- test/Common/src/Common/Service/Table/Formatter/AccessedCorrespondenceTest.php
Make documents table documents open in new browser tab.
Related issue: [VOL-5526](https://dvsa.atlassian.net/browse/VOL-5526)
> feat: Make document links open in new browser window

- Common/src/Common/FeatureToggle.php
Add feature toggle for transport consultant role
Related issue: [VOL-5249](https://dvsa.atlassian.net/browse/VOL-5249)
> feat: VOL-5249 add feature toggle for transport consultant role

- Common/src/Common/assets/js/inline/type-of-licence.js
Changes approach to show/hide the radio button to avoid `style="display: block;"` ending up in the element.
Related issue: [VOL-5665](https://dvsa.atlassian.net/browse/VOL-5665)
> fix: Special Restricted radio alignment

- Common/src/Common/Service/Table/Formatter/InternalConversationLink.php
- test/Common/src/Common/Service/Table/Formatter/InternalConversationLinkTest.php
fix: Fix messaging status case - add missing test for Formatter.
> fix: Message status tags - case fix and add unit test for Formatter.

- Common/src/Common/RefData.php
Related issue: [VOL-5305](https://dvsa.atlassian.net/browse/VOL-5305)
> feat: VOL-5305 add TC Consultant role

- Common/src/Common/View/Helper/ReturnToAddress.php
- test/Common/src/Common/View/Helper/ReturnToAddressTest.php
Related issue: [VOL-5748](https://dvsa.atlassian.net/browse/VOL-5748)
> feat: VOL-5748 update ReturnToAddress formatter for Quarry House

- Common/config/language/partials/en_GB/markup-traffic-area.phtml
- Common/view/partials/office-address.phtml
Related issue: [VOL-5536](https://dvsa.atlassian.net/browse/VOL-5536)
> feat: VOL-5536 update addresses to the new Quarry House

- Common/src/Common/Controller/Lva/AbstractOperatingCentresController.php
- Common/src/Common/Data/Mapper/Lva/FinancialEvidence.php
- Common/src/Common/Data/Mapper/Lva/OperatingCentre.php
- Common/src/Common/Form/Model/Form/Continuation/Fieldset/FinancialEvidenceRequired.php
- Common/src/Common/Form/Model/Form/Lva/Fieldset/Advertisements.php
- Common/src/Common/Form/Model/Form/Lva/Fieldset/FinancialEvidenceEvidence.php
- Common/src/Common/FormService/Form/Lva/FinancialEvidence.php
- Common/src/Common/assets/js/inline/financial-evidence.js
- test/Common/src/Common/Data/Mapper/Lva/FinancialEvidenceTest.php
- test/Common/src/Common/Data/Mapper/Lva/OperatingCentreTest.php
- test/Common/src/Common/FormService/Form/Lva/FinancialEvidenceTest.php
- test/Common/src/Common/FormService/Form/Lva/VariationFinancialEvidenceTest.php
Remove SendByPost radio options
Related issue: [VOL-5393](VOL-5393)
> feat: remove send by post radios

- Common/config/language/partials/cy_GB/markup-financial-evidence-upload-later.phtml
- Common/config/language/partials/en_GB/markup-financial-evidence-upload-later.phtml
- Common/src/Common/Form/Model/Form/Lva/Fieldset/FinancialEvidenceEvidence.php
Related issue: [VOL-5798](https://dvsa.atlassian.net/browse/VOL-5798)
> fix: VOL-5798 fix formatting for file upload radio buttons

- Common/src/Common/Rbac/User.php
- test/Common/src/Common/Rbac/UserTest.php
It's now possible to check in the identity provider whether T&Cs have been agreed
Related issue: [VOL-5664](https://dvsa.atlassian.net/browse/VOL-5664)
> feat: check whether terms agreed VOL-5664

- Common/src/Common/Form/Elements/Types/FileUploadList.php
> Revert "feat: notify user document has been uploaded"

- Common/config/module.config.php
- Common/src/Common/Validator/MustRemainOperatorAdmin.php
- test/Common/src/Common/Validator/MustRemainOperatorAdminTest.php
Related issue: [VOL-5918](https://dvsa.atlassian.net/browse/VOL-5918)
> feat: added new validator to make sure user is operator admin VOL-5918

- Common/src/Common/Data/Object/Search/SearchAbstract.php
Related issue: [VOL-6064](https://dvsa.atlassian.net/browse/VOL-6064)
> fix: VOL-6064 internal search navigation now follows GDS pattern

- Common/src/Common/Service/Data/MessagingSubject.php
Related issue: [VOL-6069](https://dvsa.atlassian.net/browse/VOL-6069)
[VOL-6069]: https://dvsa.atlassian.net/browse/VOL-6069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: filter messaging subjects by active categories VOL-6069

- Common/src/Common/Controller/Lva/AbstractVehiclesDeclarationsController.php
- Common/src/Common/Form/Model/Form/Lva/Fieldset/VehiclesDeclarationsSmallVehiclesIntention.php
- Common/src/Common/assets/js/inline/vehicle-declarations.js
Change small vehicles conditions and undertakings page.
Related issue: [5903](https://dvsa.atlassian.net/browse/VOL-5903)
https://github.com/dvsa/vol-app/pull/747
> feat: change small vehicles conditions and undertakings page

- Common/config/language/partials/cy_GB/markup-terms-and-conditions.phtml
- Common/config/language/partials/en_GB/markup-terms-and-conditions.phtml
Related issue: [VOL-6287](https://dvsa.atlassian.net/browse/VOL-6287)
[VOL-6287]: https://dvsa.atlassian.net/browse/VOL-6287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: new sections on Ts ans Cs plus updated markup to meet GDS

- Common/config/language/partials/cy_GB/markup-main-occupation-criteria-guidance.phtml
- Common/config/language/partials/en_GB/markup-main-occupation-criteria-guidance.phtml
- Common/src/Common/Controller/GuidesController.php
Related issue: [VOL-5871](https://dvsa.atlassian.net/browse/VOL-5871)
[VOL-5871]: https://dvsa.atlassian.net/browse/VOL-5871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: new main occupation criteria guidance page

- Common/config/language/partials/cy_GB/markup-main-occupation-criteria-guidance.phtml
- Common/config/language/partials/en_GB/markup-main-occupation-criteria-guidance.phtml
- Common/src/Common/Controller/GuidesController.php
Related issue: [VOL-5871](https://dvsa.atlassian.net/browse/VOL-5871)
[VOL-5871]: https://dvsa.atlassian.net/browse/VOL-5871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: made changes to make up to fix irregularities VOL 5871

- Common/config/language/partials/cy_GB/markup-terms-and-conditions.phtml
- Common/config/language/partials/en_GB/markup-terms-and-conditions.phtml
Updated the terms and conditions page to reflect the changes the OTC has asked for, in both english and welsh 
Related issue: [VOL-6298](https://dvsa.atlassian.net/browse/VOL-6298)
[VOL-6298]: https://dvsa.atlassian.net/browse/VOL-6298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: updated terms-and-conditions pages

- Common/config/language/partials/cy_GB/markup-terms-and-conditions.phtml
- Common/config/language/partials/en_GB/markup-terms-and-conditions.phtml
Related issue: [VOL-6319](https://dvsa.atlassian.net/browse/VOL-6319)
[VOL-6319]: https://dvsa.atlassian.net/browse/VOL-6319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: added missing brackets in the legislation for Ts&Cs

- composer.json
Related issue: [VOL-5649](https://dvsa.atlassian.net/browse/VOL-5649)
[VOL-5649]: https://dvsa.atlassian.net/browse/VOL-5649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: vol-5649 - bumped olcs-transfer version
